### ISSUE TITLE
Support for more clients than 254

### ISSUE THREAD

**Issue by afzl-wtu** [leonovk/wg-rest-api#70]
Please add support for more client devices as on production vpn there are many devices connected at one time.

**Comment by leonovk** [comment]
Now you can set the environment variable "CONNECTING_CLIENT_LIMIT" to set this setting. By default it is 24

**Comment by BeppeMarnell** [comment]
@leonovk Could you add this "CONNECTING_CLIENT_LIMIT " variable in the redme documentation please? Is there a minimum or a maximum number of clients allowed?
Also I would like to know some more information on the logic behind ip assignment. 
- What happens if all "CONNECTING_CLIENT_LIMIT" ips are used? 
- How are ips generated? E.g. in the cases that I set CONNECTING_CLIENT_LIMIT to 300, we start by 10.8.0.x, then I would assume that after 255 ips (not counting the server) we have ips starting with 10.8.1.x ?

**Comment by leonovk** [comment]
@BeppeMarnell ok. i do this letter

**Comment by leonovk** [comment]
@BeppeMarnell https://github.com/leonovk/wg-rest-api/wiki/Settings-you-can-set

**Comment by BeppeMarnell** [comment]
@leonovk Thank you. As far as i can see, once 255(-1 the server) ips are all assigned (with CONNECTING_CLIENT_LIMIT=24), I don't see a mechanism to trace back the deleted ips and reassign them to new Peers. Therefore if more peers are added we will get an error.
Is this correct?

**Comment by leonovk** [comment]
@BeppeMarnell To be honest, I haven't tested this case. But in theory, the wireguard server will simply crash with an error when trying to add a new key with a similar configuration. And you will need to change the config and restart the application. To make the maximum number of possible addresses, you need to set 0 in the setting.
